slick {
  dbs {
    default {
      profile = "slick.jdbc.MySQLProfile$"
      db {
        driver = "com.mysql.jdbc.Driver"
        url = "jdbc:mysql://localhost:3306/ecommerce_cart?useSSL=false&characterEncoding=utf8&serverTimezone=UTC"
        user = "root"        # 数据库用户名
        password = "123456"  # 数据库密码
        connectionPool = disabled  # 强制禁用连接池
        keepAliveConnection = true
      }
    }
  }
}